# Generated by Django 5.2.3 on 2025-07-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone_number", "0002_alter_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
