# Generated by Django 5.2.3 on 2025-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_number', '0004_contact_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
